# Generated by Django 5.2.11 on 2026-02-25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_feeding"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Cats",
            new_name="Cat",
        ),
    ]
